/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mydemoapp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Properties;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import java.util.Date;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class MyUI extends javax.swing.JFrame implements ItemListener {
    //Business business;
    
    String SelectedAttribute;
    ArrayList<String> activeCategories;
    TreeSet<String> subCategories;
    ArrayList<String> aSubCategories;
    TreeSet<String> attributes;
    ArrayList<String> selattri;
    Date member;
    UtilDateModel userDateModel;
    UtilDateModel from;
    UtilDateModel to;
    String s;
   
    /**
     * Creates new form MyUI
     */
    public MyUI() {
        initComponents();
        
        SelectedAttribute=jComboBox1.getSelectedItem().toString();
        this.activeCategories = new ArrayList();
        this.subCategories=new TreeSet();
        this.aSubCategories=new ArrayList();
        this.attributes=new TreeSet();
        this.selattri=new ArrayList();
        this.userDateModel  = new UtilDateModel();
        this.from=new UtilDateModel();
        this.to=new UtilDateModel();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jrcount = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setBackground(new java.awt.Color(0, 153, 255));
        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setText("                                                                                         Users");

        jLabel13.setText("Review Count");

        jLabel14.setText("Number of Friends");

        jLabel15.setText("Average Stars");

        jLabel16.setText("Number of Votes");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));

        jLabel17.setText("Value");

        jLabel18.setText("Value");

        jLabel19.setText("Value");

        jLabel20.setText("Value");

        jrcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrcountActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AND", "OR" }));
        jComboBox8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                StateChangeBusiness(evt);
            }
        });

        jButton1.setText("Execute Query");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        jLabel22.setText("   Result");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Yelping_Since", "Avg.Stars"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel21.setText("Search For:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrcount, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jrcount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(911, 911, 911))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("User", jPanel6);

        jScrollPane6.setViewportView(jPanel1);

        jScrollPane7.setViewportView(jPanel3);

        jScrollPane8.setViewportView(jPanel4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AND", "OR" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                State(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Business", "city", "state", "stars"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jTextPane1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Stars:");

        jLabel8.setText("Value");

        jLabel9.setText("Votes");

        jLabel10.setText("Value");

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, 124, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("                         Business");

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("    Category");

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("  Sub-Category");

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("      Attribute");

        jLabel5.setText("Search For");

        jLabel6.setText("                     Review");

        jButton3.setText("Execute Query");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Result");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane9.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(363, 363, 363))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196)
                .addComponent(jLabel12)
                .addGap(273, 273, 273))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(116, 116, 116))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Business", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void State(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_State
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED){
            SelectedAttribute=evt.getItem().toString();
        }
    }//GEN-LAST:event_State

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jrcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrcountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrcountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      this.getTable();
        
        
        
        //model=(DefaultTableModel) jTable2.getModel();
        //model.setRowCount(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> categories;
        Connection conn = null;
        ResultSet resultSet = null;
        ArrayList<String> data=new ArrayList();
        ArrayList<String> attributes;
        ArrayList<String> Mcategories;
        try {
            Mcategories = this.activeCategories;
            categories = this.aSubCategories;
            attributes=this.selattri;
            Float astar = null;
            DefaultTableModel model;
            model=(DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            if(jTextField1.getText()!=null&&jTextField1.getText().length()>0){
                astar=Float.parseFloat(jTextField1.getText());
            }
           
            String astarcomb=jComboBox2.getSelectedItem().toString();//average stars =,<,>
            String nvotes=jComboBox3.getSelectedItem().toString();// number of votes =,>,<
            Integer nvote = null;
            if(jTextField2.getText().length()>0){
                nvote=Integer.parseInt(jTextField2.getText());
            }
            s="Select Name,city,state,stars from yelp_business where ";
            if(categories.size()>0 && attributes.size()>0){
                
                for(int i = 0; i < this.activeCategories.size(); i++){
                    for(int j=0;j<this.aSubCategories.size();j++){
                        for(int k=0;k<this.selattri.size();k++){
                            //System.out.println(SelectedAttribute);
                            s = s + "(categories like '%" + this.activeCategories.get(i) + "%' AND categories like '%"+this.aSubCategories.get(j) +"%' AND attributes like '%"+this.selattri.get(k)+"%')";
                            if(i+j+k<(this.activeCategories.size()+this.aSubCategories.size()+this.selattri.size()-3)){
                                s=s+" "+SelectedAttribute+" ";
                            }
                        }
                    }
                }
            }
            else if(categories.size()>0){
                for(int i = 0; i < this.activeCategories.size(); i++){
                    for(int j=0;j<this.aSubCategories.size();j++){
                        
                        s = s + "(categories like '%" + this.activeCategories.get(i) + "%' AND categories like '%"+this.aSubCategories.get(j) +"%')";
                        if(i+j<(this.activeCategories.size()+this.aSubCategories.size()-2)){
                            s=s+" "+SelectedAttribute+" ";
                        }
                    }
                }
            }
            else{
                for(int i = 0; i < this.activeCategories.size(); i++){
                    if(i > 0 && i < this.activeCategories.size()){
                        s=s+" "+SelectedAttribute+" ";
                    }
                    //System.out.println(SelectedAttribute);
                    s = s + "categories like '%" + this.activeCategories.get(i) + "%'";
                    
                }
            }
            if(astar!=null){
                s=s+" "+SelectedAttribute+" stars"+astarcomb+astar;
            }
            if(nvote!=null){
                s=s+" "+SelectedAttribute+" business_id in (select business_id from userCount where nvotes"+nvotes+nvote+")";
            }
            Date f=(Date)this.from.getValue();
            Date t=(Date)this.to.getValue();
            System.out.println(f);
            System.out.println(t);
            if(t!=null && f!=null){
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                 String toDate = df.format(t);
                 System.out.println(toDate);
                 String fromDate = df.format(f);
                 System.out.println(fromDate);
                 if(!fromDate.isEmpty() && !toDate.isEmpty()){
                     s=s+" "+SelectedAttribute+ " "+"business_id in (select business_id from yelp_review where rdate>TO_DATE('"+fromDate+"', 'YYYY-MM-DD') and rdate<TO_DATE('"+toDate+"', 'YYYY-MM-DD'))";
                     
                 }
            }
            System.out.println(s);
            jTextPane1.setText(s);
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","System","oracle");
            Statement stmt = conn.createStatement();
            resultSet=stmt.executeQuery(s);
            
            
            if (!resultSet.isBeforeFirst() ) {
                System.out.println("No data");
            } 
            long start = System.currentTimeMillis();
            while(resultSet.next()){
                //System.out.println("\n"+resultSet.getString(1) + "\t"+resultSet.getString(2)+ "\t"+resultSet.getString(3)+ "\t"+resultSet.getInt(4));
                String d=resultSet.getString(1)+","+resultSet.getString(2)+","+resultSet.getString(3)+","+resultSet.getInt(4);
                model.addRow(new Object[]{
                    resultSet.getString(1),
                    resultSet.getString(2),
                    resultSet.getString(3),
                    resultSet.getInt(4)
                });
            }
            long end = System.currentTimeMillis();
            float sec = (end - start) / 1000F; System.out.println(sec + " seconds For business table");
            
            jTable1.setVisible(true);
            jTable1.setRowSelectionAllowed(true);
            jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent event) {
                    // do some actions here, for example
                    boolean adjust = event.getValueIsAdjusting();
                   if (!adjust) {
                        // print first column value from selected row
                        //String st="Select u.name, r.text from yelp_review r where business_id in (Select business_id from yelp_business where name like '"+jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()+"')" inner join on yelp_user ;
                        //String st="Select u.name,r.text from yelp_review r inner join yelp_user u on r.user_id=u.user_id where r.business_id in (Select business_id from yelp_business where name="+jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()+")";
                        
                        
                        //System.out.println(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
                        try{
                            String st="Select u.name,r.text from yelp_review r inner join yelp_user u on r.user_id=u.user_id where r.business_id in (Select business_id from yelp_business where name like '%"+jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()+"%')";
                            System.out.println(st);
                            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","System","oracle");
                            Statement state = con.createStatement();
                            ResultSet resultSet=state.executeQuery(st);
                            String d="";
                            long start=System.currentTimeMillis();
                            while(resultSet.next()){
                                d=d+resultSet.getString(1)+": "+resultSet.getString(2)+"\n";
                            }
                            long end = System.currentTimeMillis();
                            float sec = (end - start) / 1000F;
                            System.out.println(sec + " seconds For Reviews in business");
                            
                            jTextArea3.setText(d);
                            jTextArea3.repaint();
                            con.close();
                            
                        }
                        
                        catch(Exception E){
                            System.out.println("SQLException:"+E.getMessage());
                        }
                    }
                }
            });
            conn.close();
            
        }catch (SQLException ex) {
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void StateChangeBusiness(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_StateChangeBusiness
        // TODO add your handling code here:
        
    }//GEN-LAST:event_StateChangeBusiness

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        MyUI m = new MyUI();
        
        
        
        // 2. Make Application Visible.
        /* Create and display the form */
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // build business Panel
                m.buildBusinessCategoryPanel();
              
                
                 m.InsertCheck1();
                 m.setVisible(true);
                 m.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               
        
                
            }


            
        });
         
    }
    
    private void buildBusinessCategoryPanel() {
        
        ArrayList<String> categories = this.getCategories();
        Box box = Box.createVerticalBox();
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.repaint();
        for (int i = 0; i < categories.size(); i++) {
            JCheckBox checkbox = new JCheckBox(categories.get(i));
            checkbox.setName("category:"+categories.get(i));
            checkbox.addItemListener(this);
            //checkbox.addItemListener(this);
            box.add(checkbox);
        }
        
        jPanel1.add(box);
        
    }
    private void buildSubCategoryPanel() {
        try {
            
            TreeSet<String> categories = this.getSubcategories();
            Box box = Box.createVerticalBox();
            jPanel3.removeAll();
            jPanel3.revalidate();
            jPanel3.repaint();
            for (String temp : categories) {
                JCheckBox checkbox = new JCheckBox(temp);
                checkbox.setName("subcategory:"+temp);
                checkbox.addItemListener(this);
                box.add(checkbox);
            }
            
            
            jPanel3.add(box);
        } catch (SQLException ex) {
            Logger.getLogger(MyUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void attributePanel(){
        try{
            TreeSet<String> attributes=this.getattributes();
            Box box = Box.createVerticalBox();
            jPanel4.removeAll();
            jPanel4.revalidate();
            jPanel4.repaint();
            
            for (String temp : attributes) {
                JCheckBox checkbox = new JCheckBox(temp);
                checkbox.setName("attribute"+temp);
                checkbox.addItemListener(this);
                box.add(checkbox);
            }
            
            
            jPanel4.add(box);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(MyUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    public ArrayList getCategories() {
        ArrayList<String> main_categories = new ArrayList<String>();
        main_categories.add("Active Life");
        main_categories.add("Arts & Entertainment");
        main_categories.add("Automotive");
        main_categories.add("Car Rental");
        main_categories.add("Cafes");
        main_categories.add("Beauty & Spas");
        main_categories.add("Convenience Stores");
        main_categories.add("Dentists");
        main_categories.add("Doctors");
        main_categories.add("Drugstores");
        main_categories.add("Department Stores");
        main_categories.add("Education");
        main_categories.add("Event Planning & Services");
        main_categories.add("Flowers & Gifts");
        main_categories.add("Food");
        main_categories.add("Health & Medical");
        main_categories.add("Home Services");
        main_categories.add("Home & Garden");
        main_categories.add("Hospitals");
        main_categories.add("Hotels & Travel");
        main_categories.add("Hardware Stores");
        main_categories.add("Grocery");
        main_categories.add("Medical Centers");
        main_categories.add("Nurseries & Gardening");
        main_categories.add("Nightlife");
        main_categories.add("Restaurants");
        main_categories.add("Shopping");
        main_categories.add("Transportation");
        
        return main_categories;
    }
    
    public TreeSet getSubcategories() throws SQLException{
        
        s="Select sub_category from cat where ";
        for(int i = 0; i < this.activeCategories.size(); i++){
            if(i > 0 && i < this.activeCategories.size()){
                s=s+" "+SelectedAttribute+" ";
            }
            //System.out.println(SelectedAttribute);
            s = s + "category like '%" + this.activeCategories.get(i) + "%'";
            
        }
        
        
        
        System.out.println(s);
        this.subCategories.clear();
        try{
            long startTime = System.nanoTime();
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","System","oracle");
            Statement state = con.createStatement();
            ResultSet resultSet=state.executeQuery(s);
                        
            

            while(resultSet.next()){
                String sub=resultSet.getString(1);
                if(resultSet.getString(1).length()>2){
                    sub=sub.substring(1, sub.length()-1);
                    String [] subc=sub.split(",");
                    for(int j=0;j<subc.length;j++){
                        subc[j].trim();
                        if(subc[j]!=null){
                            this.subCategories.add(subc[j]);
                        }
                    }
                }
            }
            long endTime   = System.nanoTime();
            long totalTime = endTime - startTime;
            
        } catch(Exception e){
            System.out.println(e);
        }
        return this.subCategories;
    }
    
    public TreeSet getattributes() throws SQLException{
        s="Select attributes from yelp_business where ";
        for(int i = 0; i < this.activeCategories.size(); i++){
            for(int j=0;j<this.aSubCategories.size();j++){
            
            System.out.println(SelectedAttribute);
            s = s + "(categories like '%" + this.activeCategories.get(i) + "%' AND categories like '%"+this.aSubCategories.get(j) +"%')";
            if(i+j<(this.activeCategories.size()+this.aSubCategories.size()-2)){
                s=s+" "+SelectedAttribute+" ";
            }
            } 
        }
        
        
        //System.out.println(s);
        
        try{
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","System","oracle");
            Statement state = con.createStatement();
            ResultSet resultSet=state.executeQuery(s);
                        
           
            while(resultSet.next()){
                String sub=resultSet.getString(1);
                if(resultSet.getString(1).length()>2){
                    sub=sub.substring(1, sub.length()-1);
                    String [] subc=sub.split(",");
                    for(int j=0;j<subc.length;j++){
                        
                        subc[j]=subc[j].trim();
                        subc[j]=subc[j].replace(" ","_");
                        subc[j]=subc[j].replace(":", "_");
                        subc[j]=subc[j].replace("\"", "");
                        subc[j]=subc[j].replace("{", "");
                        subc[j]=subc[j].replace("}", "");
                        if(subc[j]!=null){
                            this.attributes.add(subc[j]);
                        }
                    }
                }
            }
        } catch(Exception e){
            System.out.println(e);
        }
        return this.attributes;
    }
    
    
    
    public void getTable(){
        Connection conn = null;
        ResultSet resultSet = null;
        ArrayList<String> data=new ArrayList();
        Integer nfri=null;
        Float astar=null;
        String rcount=null;
        Integer nvote=null;
        String s="";
        String comb=jComboBox8.getSelectedItem().toString();// AND,OR
        String rccomb=jComboBox4.getSelectedItem().toString();//review count =,>,<
        String nfricomb=jComboBox5.getSelectedItem().toString();//no of friends =,>,<
        String astarcomb=jComboBox6.getSelectedItem().toString();//average stars =,<,>
        String nvotes=jComboBox7.getSelectedItem().toString();// number of votes =,>,<
        int c=0;
        DefaultTableModel model;
        model=(DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        try {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","System","oracle");
        } catch(Exception E){
            System.out.println("SQLException:"+E.getMessage());
        }
        int count=0;
        s="Select name,yelping_since,average_stars from yelp_user where";
        if(jrcount.getText().length()>0){
            rcount=jrcount.getText();
            if(count>0){
                s=s+" "+comb+" ";
            }
            s=s+" review_count "+rccomb+" "+rcount;
            count++;
        }
        if(jTextField4.getText().length()>0){
            nfri=Integer.parseInt(jTextField4.getText());
             }
        if(jTextField5.getText().length()>0){
            astar=Float.parseFloat(jTextField5.getText());
            if(count>0){
                s=s+" "+comb+" ";
            }
            s=s+" average_stars "+astarcomb+" "+astar;
            count++;
        }
        if(jTextField6.getText().length()>0){
            nvote=Integer.parseInt(jTextField6.getText());
        }
        if(nfri!=null || nvote!=null){
            if(nfri!=null && nvote!=null){
                if(count>0){
                    s=s+" "+comb+" ";
                }
                s=s+" user_id in (select user_id from userCount where nfriends "+nfricomb+" "+nfri+" "+comb+" nvotes "+nvotes+" "+nvote+")";
                count++;
                
            }
            else if(nfri!=null){
                if(count>0){
                    s=s+" "+comb+" ";
                }
                s=s+" user_id in (select user_id from userCount where nfriends "+nfricomb+" "+nfri+")";
                count++;
            }
            else if(nvote!=null){
                if(count>0){
                    s=s+" "+comb+" ";
                }
                
                s=s+" user_id in (select user_id from userCount where nvotes "+nvotes+" "+nvote+")";
                count++;
            }
        }
        Date date=(Date)this.userDateModel.getValue();
        System.out.println(date);
        if(date!=null){
                DateFormat df = new SimpleDateFormat("yyyy-MM");
                 String reportDate = df.format(date);
                  System.out.println(reportDate);
                 if(count>0){
                     s=s+" "+comb+" ";
                 }
                 if(!reportDate.isEmpty()){
                     s=s+" yelping_since= TO_DATE('"+reportDate+"', 'YYYY-MM')";
                     count++;
                 }
            }
      
        
        //s="Select name,yelping_since,average_stars from yelp_user where review_count "+rccomb+" "+rcount+" "+comb+" average_stars "+astarcomb+" "+astar+" "+comb+" yelping_since= TO_DATE('"+reportDate+"', 'YYYY-MM')"+" "+comb+" user_id in (select user_id from userCount where nfriends "+nfricomb+" "+nfri+" "+comb+" nvotes "+nvotes+" "+nvote+")";
        System.out.println(s+"******user");
        jTextArea2.setText(s);
        jTextArea2.repaint();
        try{
        Statement stmt = conn.createStatement();
        resultSet=stmt.executeQuery(s);
        int i=0;
        if (!resultSet.isBeforeFirst() ) {
            System.out.println("No data");
        } 
        long start = System.currentTimeMillis();
        while(resultSet.next()){
            //System.out.println("\n"+resultSet.getString(1) + "\t"+resultSet.getDate(2)+ "\t"+resultSet.getLong(3));
            
            String d=resultSet.getString(1)+","+resultSet.getDate(2)+","+resultSet.getLong(3);
            model.addRow(new Object[]{
                resultSet.getString(1),
                resultSet.getDate(2),
                resultSet.getLong(3)
            });
          
           
            
        }
        long end = System.currentTimeMillis();
        float sec = (end - start) / 1000F; System.out.println(sec + " seconds For user Table");
        jTable2.setVisible(true);
        jTable2.setRowSelectionAllowed(true);
        jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            // do some actions here, for example
            // print first column value from selected row
            boolean adjust = event.getValueIsAdjusting();
            if (!adjust) {
                //System.out.println(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
                try{
                    
                    
                    String st="Select text from yelp_review where user_id in (Select user_id from yelp_user where name like '%"+jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()+"%')";
                    System.out.println(st);
                    Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","System","oracle");
                    Statement state = con.createStatement();
                    ResultSet resultSet=state.executeQuery(st);
                    String d="";
                    long start = System.currentTimeMillis();
                    while(resultSet.next()){
                        d=d+resultSet.getString(1)+"\n";
                        
                        
                    }
                    long end = System.currentTimeMillis();
                    float sec = (end - start) / 1000F; System.out.println(sec + " seconds For user Reviews");
                    
                    
                    jTextArea1.setText(d);
                    jTextArea1.repaint();
                    con.close();
                    
                }
                
                catch(Exception E){
                    System.out.println("SQLException:"+E.getMessage());
                }
            }
        }
        });
        
         conn.close();
         }
       
        catch(Exception E){
            System.out.println("SQLException:"+E.getMessage());
        }
        
       
    }
    
    
    
   public void InsertCheck1(){
//        Box box = Box.createVerticalBox();
//        for (int i = 0; i < 30; i++) {
//            JCheckBox checkbox = new JCheckBox();
//            //checkbox.addItemListener(this);
//            box.add(checkbox);
//        }
//        jPanel1.add(box);  
        Properties p = new Properties();
        p.put("text.today", "Today");
        p.put("text.month", "Month");
        p.put("text.year", "Year");
        
        this.from.setDate(1990, 8, 24);
        JDatePanelImpl datePanel = new JDatePanelImpl(this.from, p);
        JDatePickerImpl datePicker = new JDatePickerImpl(datePanel,new DateLabelFormatter());
        
        jPanel7.add(new JLabel("From"));
        jPanel7.add(datePicker);
        
        
        
        this.to.setDate(1990, 8, 25);
        JDatePanelImpl datePanel1 = new JDatePanelImpl(this.to, p);
        JDatePickerImpl datePicker1 = new JDatePickerImpl(datePanel1,new DateLabelFormatter());
        jPanel7.add(new JLabel("To"));
        jPanel7.add(datePicker1);   
        
        
        // User date
        this.userDateModel.setDate(1990, 8, 25);
        JDatePanelImpl datePanel2 = new JDatePanelImpl(this.userDateModel, p);
        JDatePickerImpl datePicker2 = new JDatePickerImpl(datePanel2,new DateLabelFormatter());
        
        jPanel8.add(new JLabel("Member Since"));
        jPanel8.add(datePicker2);
        

        // run
    }
 
    
    
    

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField jrcount;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
         //To change body of generated methods, choose Tools | Templates.
        JCheckBox check = (JCheckBox)e.getSource();
         String itemName = check.getName();
         System.out.println(itemName);
        
        String [] itemNameArray=itemName.split(":");
        
        if("category".equals(itemNameArray[0])){
            
            if (e.getStateChange() ==ItemEvent.SELECTED){
                this.activeCategories.add(itemNameArray[1]);
            }
            else if(e.getStateChange() ==ItemEvent.DESELECTED){
                this.activeCategories.remove(itemNameArray[1]);
            }
            
            // build subcategories
            this.buildSubCategoryPanel();
            
        }
        if("subcategory".equals(itemNameArray[0])){
            
            if (e.getStateChange() ==ItemEvent.SELECTED){
                this.aSubCategories.add(itemNameArray[1]);
            }
            else if(e.getStateChange() ==ItemEvent.DESELECTED){
                this.aSubCategories.remove(itemNameArray[1]);
            }
            
            // build attributes
            
            this.attributePanel();
            
        }
        if("attribute".equals(itemNameArray[0])){
            if (e.getStateChange() ==ItemEvent.SELECTED){
                this.selattri.add(itemNameArray[1]);
            }
            else if(e.getStateChange() ==ItemEvent.DESELECTED){
                this.selattri.remove(itemNameArray[1]);
            }
        }
    
         
        
         
    }

    
}

  
